// Category Actions
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const LOAD_CATEGORY_SUCCESS = 'LOAD_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
// Category modal actions
export const TOGGLE_CONFIRM_DELETE_CATEGORY_MODAL =
  'TOGGLE_CONFIRM_DELETE_CATEGORY_MODAL';
export const TOGGLE_CATEGORY_MODAL = 'TOGGLE_CATEGORY_MODAL';

// Items Actions
export const LOAD_ITEMS_SUCCESS = 'LOAD_ITEMS_SUCCESS';
export const LOAD_ITEMS_BY_CATEGORY_SUCCESS = 'LOAD_ITEMS_BY_CATEGORY_SUCCESS';
export const LOAD_ITEM_SUCCESS = 'LOAD_ITEM_SUCCESS';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
// Item modal actions
export const TOGGLE_CONFIRM_DELETE_ITEM_MODAL =
  'TOGGLE_CONFIRM_DELETE_ITEM_MODAL';
export const TOGGLE_ITEM_MODAL = 'TOGGLE_ITEM_MODAL';

// Auth Actions
export const USER_LOGGED_IN_SUCCESS = 'USER_LOGGED_IN_SUCCESS';
export const USER_LOGGED_OUT_SUCCESS = 'USER_LOGGED_OUT_SUCCESS';
export const USER_LOGGED_IN_FAILED = 'USER_LOGGED_IN_FAILED';
